/**
 * Schema VFS — placeholder module.
 *
 * At runtime, the build/schema-vfs.ts Bun plugin intercepts this module
 * and replaces all exports with actual schema file contents from schema/.
 *
 * This file exists only as an import target and for TypeScript type inference.
 * The actual code is generated by the plugin.
 */
export const schemaFiles: Record<string, string> = {};

export interface SchemaDir {
	path: string;
	cleanup(): void;
}

export declare function extractSchema(): SchemaDir;
