// Auto-generated by scripts/generate-schema-manifest.ts
// Do not edit manually. Run: bun run generate:schema
import f0 from "./schema.sql";

export const schemaFiles: Record<string, string> = {
	"schema.sql": f0,
};
