/**
 * Scans server/schema/ for all *.sql files and generates
 * server/schema/manifest.ts with static imports.
 *
 * Run: bun run scripts/generate-schema-manifest.ts
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const SCHEMA_DIR = join(import.meta.dir, "../schema");
const MANIFEST_PATH = join(SCHEMA_DIR, "manifest.ts");

function collectSqlFiles(dir: string, base: string): string[] {
	const entries = readdirSync(dir);
	const files: string[] = [];
	for (const entry of entries) {
		if (entry === "manifest.ts" || entry === "index.ts") continue;
		const fullPath = join(dir, entry);
		const stat = statSync(fullPath);
		if (stat.isDirectory()) {
			files.push(...collectSqlFiles(fullPath, base));
		} else if (entry.endsWith(".sql")) {
			files.push(relative(base, fullPath));
		}
	}
	return files.sort();
}

const sqlFiles = collectSqlFiles(SCHEMA_DIR, SCHEMA_DIR);

const imports = sqlFiles
	.map((f, i) => `import f${i} from "./${f}";`)
	.join("\n");

const entries = sqlFiles.map((f, i) => `\t"${f}": f${i},`).join("\n");

const manifest = `// Auto-generated by scripts/generate-schema-manifest.ts
// Do not edit manually. Run: bun run generate:schema
${imports}

export const schemaFiles: Record<string, string> = {
${entries}
};
`;

writeFileSync(MANIFEST_PATH, manifest);
console.log(
	`Generated schema/manifest.ts with ${sqlFiles.length} file(s): ${sqlFiles.join(", ")}`,
);
